using System.Collections.Generic;

namespace DS1Counter.Models
{
    public static class Items
    {
        private static Dictionary<int, string> _itemDictionary;

        public static string Get(int id)
        {
            string itemName = string.Empty;
            _itemDictionary.TryGetValue(id, out itemName);

            return itemName;
        }

        static Items()
        {
            _itemDictionary = new Dictionary<int, string>
            {
                {0x65, "White chalk"},
                {0x66, "Red chalk"},
                {0x67, "Red eye"},
                {0x68, "Black Separation Crystal"},
                {0x6a, "Orange chalk"},
                {0x6c, "Book of the Guilty"},
                {0x6d, "Death eye"},
                {0x6f, "Cracked red eye orb"},
                {0x70, "Servant Roster"},
                {0x71, "Blue eye orb"},
                {0x72, "Dragon eye orb"},
                {0x73, "Black eye orb"},
                {0x74, "Black eye orb #2"},
                {0x75, "Mark of the darkness"},
                {0x76, "Violet coward crystal"},
                {0x90, "Darkness sign"},
                {0xC8, "Estus Flask (empty)"},
                {0xC9, "Estus Flask (active)"},
                {0xCA, "Estus Flask (empty)"},
                {0xCB, "Estus Flask +1"},
                {0xCC, "Estus Flask +1 (empty)"},
                {0xCD, "Estus Flask +2"},
                {0xCE, "Estus Flask +3 (empty)"},
                {0xCF, "Estus Flask +3"},
                {0xD0, "Estus Flask +4 (empty)"},
                {0xD1, "Estus Flask +4"},
                {0xD2, "Estus Flask +5 (empty)"},
                {0xD3, "Estus Flask +5"},
                {0xD4, "Estus Flask +6 (empty)"},
                {0xD5, "Estus Flask +6"},
                {0xD6, "Estus Flask +7 (empty)"},
                {0xD7, "Estus Flask +7"},
                {0xDC, "Silver neckle"},
                {0xE6, "Elisabeth Mushroom"},
                {0xF0, "Heaven’s blessing"},
                {0x104, "Green flower"},
                {0x10e, "Red moss"},
                {0x10f, "Purple moss"},
                {0x110, "Purple blooming moss"},
                {0x110, "Stone of repel"},
                {0x113, "Eggs medicine"},
                {0x118, "Fixment powder"},
                {0x122, "Throwing knife"},
                {0x123, "Poisoned throwing knife"},
                {0x124, "Fire bomb"},
                {0x125, "Manure pie"},
                {0x126, "Nice skull"},
                {0x10e, "LLoyd’s charm"},
                {0x129, "Black bomb"},
                {0x136, "Black gum (resin)"},
                {0x137, "Golden gum (resin)"},
                {0x138, "Short duration damnation"},
                {0x139, "Rotten gum (resin)"},
                {0x14a, "Bone of return"},
                {0x15e, "Humanity"},
                {0x172, "Shiny stone"},
                {0x172, "Field glasses"},
                {0x175, "List of charge"},
                {0x176, "Mark (sign) of retribution"},
                {0x177, "Medal of the light"},
                {0x178, "Neckle"},
                {0x179, "Stone with gragon head"},
                {0x17a, "Stone with dragon body"},
                {0x17c, "Trash"},
                {0x17d, "Copper coin"},
                {0x17e, "Silver coin"},
                {0x17f, "Golden coin"},
                {0x180, "Strange doll"},
                {0x181, "Dried finger"},
                {0x186, "Keeper of fire soul"},
                {0x187, "Keeper of fire soul (no mistake there’s one more)"},
                {0x188, "Keeper of fire soul (no mistake there’s one more)"},
                {0x189, "Keeper of fire soul (no mistake there’s one more)"},
                {0x18a, "Keeper of fire soul (no mistake there’s one more)"},
                {0x18b, "Keeper of fire soul (no mistake there’s one more)"},
                {0x18c, "Keeper of fire soul (no mistake there’s one more)"},
                {0x190, "Soul of the lost undead"},
                {0x18e, "Big soul of the lost undead"},
                {0x18f, "Soul of nameless soldier"},
                {0x190, "Big soul of nameless soldier"},
                {0x191, "Soul of a Proud Knight"},
                {0x192, "Big soul of a Proud Knight"},
                {0x193, "Soul of a Brave Warrior"},
                {0x194, "Big soul of a Brave Warrior"},
                {0x195, "Soul of a Hero"},
                {0x196, "Soul of a Great Hero"},
                {0x1f4, "Humanity"},
                {0x1f5, "Double humanity"},
                {0x1fe, "Sign “hello”"},
                {0x1ff, "Sign “thanks”"},
                {0x200, "Sign “perfect” (gj, gd, whatever)"},
                {0x201, "Sign “sorry”"},
                {0x2BC, "Soul of Sif"},
                {0x2BD, "Soul of Quelaag"},
                {0x2BE, "Soul of Gwynn"},
                {0x2BF, "Soul of Iron Golem"},
                {0x2C0, "Soul of Ornstein"},
                {0x2C1, "Soul of Moonlight butterfly"},
                {0x2C2, "Soul of Smough"},
                {0x2C3, "Soul of Priscilla"},
                {0x2C4, "Soul of Gwyndolin"},
                {0x2C5, "Soul of Sentinel"},
                {0x2C6, "Soul of Artorias"},
                {0x2C7, "Soul of Manus"},
                {0x320, "Big coal"},
                {0x321, "Very big coal"},
                {0x322, "Crystal coal"},
                {0x326, "Big magic coal"},
                {0x327, "Charmed coal"},
                {0x328, "Heaven’s coal"},
                {0x329, "Big heaven’s coal"},
                {0x32a, "Coal of darkness"},
                {0x32c, "Big coal of fire"},
                {0x3e8, "Titanite Shard"},
                {0x3f2, "Large Titanite Shard"},
                {0x3fc, "Green Titanite Shard"},
                {0x406, "Titanite chunk"},
                {0x410, "Blue Titanite chunk"},
                {0x41a, "White Titanite chunk"},
                {0x424, "Red Titanite chunk"},
                {0x42e, "Titanite slab"},
                {0x438, "Blue Titanite slab"},
                {0x442, "White Titanite slab"},
                {0x44c, "Red Titanite slab"},
                {0x456, "Dragon scales"},
                {0x460, "Demonic titanite"},
                {0x46a, "Twinkling titanite"},
                {0x7d1, "Cellar Key"},
                {0x7d2, "Artorias symbol"},
                {0x7d3, "Cage Key"},
                {0x7d4, "Archive’s prison key"},
                {0x7d5, "–The– Key"},
                {0x7d6, "–The– Key"},
                {0x7d7, "–The– Key"},
                {0x7d8, "–The– Key"},
                {0x7d9, "–The– Key"},
                {0x7da, "–The– Key"},
                {0x7db, "–The– Key"},
                {0x7dc, "–The– Key"},
                {0x7dd, "–The– Key"},
                {0x7de, "–The– Key"},
                {0x7df, "–The– Key"},
                {0x7e0, "–The– Key"},
                {0x7e1, "–The– Key"},
                {0x7e2, "–The– Key"},
                {0x7e3, "–The– Key"},
                {0x7e4, "–The– Key"},
                {0x7e5, "–The– Key"},
                {0x7e6, "–The– Key"},
                {0x9c4, "The Great Soul"},
                {0x9c5, "The Great Soul #2"},
                {0x9c6, "Shard of great soul"},
                {0x9c7, "Shard of great soul #2"},
                {0x9ce, "Lordvessel"},
                {0x9d8, "Broken neckle"},
                {0xa28, "Blacksmith’s box"},
                {0xa29, "Blacksmith’s armour box"},
                {0xa2a, "Repair’s box"},
                {0xa2b, "Unknown Receipt #1"},
                {0xa2c, "Unknown key #1"},
                {0xa2d, "Unknown key #2"},
                {0xa2e, "Unknown key #3"},
                {0xa2f, "Rite of Kindling"},
                {0xa30, "Limitless box"},
                {0xa2f, "Unknown key #4"},
                {0xbb8, "Sorcery: soul arrow"},
                {0xbc2, "Sorcery: big soul arrow"},
                {0xbcc, "Sorcery: heavy soul arrow"},
                {0xbd6, "Sorcery: huge soul arrow"},
                {0xbe0, "Sorcery: Homing Soulmass"},
                {0xbea, "Sorcery: Crystal Soulmass"},
                {0xbf4, "Sorcery: Soul spear"},
                {0xbfe, "Sorcery: Crystal soul spear"},
                {0xc1c, "Magic weapon"},
                {0xc26, "Sorcery: big magic weapon"},
                {0xc30, "Sorcery: crystal magic weapon"},
                {0xce4, "Sorcery: magic shield"},
                {0xcee, "Sorcery: strong magic shield"},
                {0xd48, "Sorcery: hidden weapon"},
                {0xd52, "Sorcery: hidden body"},
                {0xd52, "Sorcery: cast light"},
                {0xdb6, "Sorcery: hush"},
                {0xdca, "Sorcery: repair"},
                {0xdd4, "Sorcery: fall control"},
                {0xdde, "Sorcery: chameleon"},
                {0xe10, "Sorcery: resist Curse"},
                {0xe1a, "Sorcery: cure"},
                {0xe74, "Sorcery: breath of the white dragon"},
                {0xe7e, "Sorcery: dark orb"},
                {0xe88, "Sorcery: dark bead"},
                {0xe92, "Sorcery: fog of darkness"},
                {0xe9c, "Sorcery: Pursuers"},
                {0xfa0, "Pyromancy: Fire bead"},
                {0xfaa, "Pyromancy: Fire orb"},
                {0xfb4, "Pyromancy: Big fire orb"},
                {0xfbe, "Pyromancy: Fire storm"},
                {0xfc8, "Pyromancy: Fire tempest"},
                {0xfd2, "Pyromancy: Fire surge"},
                {0xfdc, "Pyromancy: Fire whip"},
                {0x1004, "Pyromancy: Combustion"},
                {0x100e, "Pyromancy: Great combustion"},
                {0x1068, "Pyromancy: Poison mist"},
                {0x1072, "Pyromancy: Toxic mist"},
                {0x107c, "Pyromancy: Acid surge"},
                {0x10cc, "Pyromancy: Iron flesh"},
                {0x10d6, "Pyromancy: Flesh sweat"},
                {0x1130, "Pyromancy: Power within"},
                {0x1194, "Pyromancy: Big chaos orb"},
                {0x119e, "Pyromancy: Chaos storm"},
                {0x11a8, "Pyromancy: Chaos fire whip"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Miracles: Heal"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"},
                {0x1388, "Emotions: Bow"}
            };
        }
    }
}
